/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_calc_Driver */

#ifndef _Included_com_calc_Driver
#define _Included_com_calc_Driver
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_calc_Driver
 * Method:    setOperand
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_com_calc_Driver_setOperand
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     com_calc_Driver
 * Method:    setOperator
 * Signature: (C)V
 */
JNIEXPORT void JNICALL Java_com_calc_Driver_setOperator
  (JNIEnv *, jobject, jchar);

/*
 * Class:     com_calc_Driver
 * Method:    result
 * Signature: ()F
 */
JNIEXPORT jfloat JNICALL Java_com_calc_Driver_result
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
